import {
  IPostmarkInboundWebhook,
  IPostmarkMessage,
} from "@/lib/types/postmark-api";
import { htmlToText } from "html-to-text";

class PostmarkWebhookParser {
  private readonly noReplyLocalPartTokens = [
    "no-reply",
    "noreply",
    "do-not-reply",
    "donotreply",
  ];

  private readonly autoGeneratedHeaderHints = [
    "auto-generated",
    "auto-replied",
    "bulk",
    "junk",
  ];

  parseInboundEmail(body: IPostmarkInboundWebhook): IPostmarkMessage {
    const msg: IPostmarkMessage = {
      id: body.MessageID,
      from: body.FromFull.Email,
      fromName: body.FromFull.Name || body.FromName,
      to: body.ToFull[0]?.Email || body.To,
      subject: body.Subject,
      textBody:
        body.TextBody ||
        htmlToText(body.HtmlBody || "", {
          wordwrap: false,
          selectors: [{ selector: "img", format: "skip" }],
        }),
      htmlBody: body.HtmlBody,
      strippedTextReply: body.StrippedTextReply,
      timestamp: body.Date,
      type: "email",
      replyTo: body.ReplyTo,
      cc: body.CcFull?.map((cc) => cc.Email),
      attachments: body.Attachments,
      mailboxHash: body.MailboxHash,
      messageStream: body.MessageStream,
      inReplyTo: this.getInReplyTo(body),
      references: this.getReferences(body),
    };

    return msg;
  }

  getInReplyTo(body: IPostmarkInboundWebhook): string | undefined {
    const header = body.Headers.find((h) => h.Name === "In-Reply-To");
    return header?.Value;
  }

  getReferences(body: IPostmarkInboundWebhook): string | undefined {
    const header = body.Headers.find((h) => h.Name === "References");
    return header?.Value;
  }

  extractRecipientEmail(toAddress: string): string {
    // Extract the email address from the To field
    // Example: "451d9b70cf9364d23ff6f9d51d870251569e+ahoy@inbound.postmarkapp.com"
    return toAddress.split("@")[0].split("+")[0];
  }

  extractMailboxHash(body: IPostmarkInboundWebhook): string {
    // Returns the mailbox hash which can be used for routing
    return body.MailboxHash;
  }

  hasAttachments(body: IPostmarkInboundWebhook): boolean {
    return body.Attachments ? body.Attachments.length > 0 : false;
  }

  getAttachmentCount(body: IPostmarkInboundWebhook): number {
    return body.Attachments?.length || 0;
  }

  isAutoReply(body: IPostmarkInboundWebhook): boolean {
    // Check common auto-reply indicators in headers
    const headers = body.Headers;
    const autoReplyHeaders = [
      "X-Autorespond",
      "X-Auto-Response-Suppress",
      "Auto-Submitted",
    ];

    return headers.some((header) => autoReplyHeaders.includes(header.Name));
  }

  getSpamScore(body: IPostmarkInboundWebhook): number | null {
    // Extract spam score from headers if available
    const spamScoreHeader = body.Headers.find((h) => h.Name === "X-Spam-Score");
    return spamScoreHeader ? parseFloat(spamScoreHeader.Value) : null;
  }

  isSpam(body: IPostmarkInboundWebhook): boolean {
    const spamStatusHeader = body.Headers.find(
      (h) => h.Name === "X-Spam-Status",
    );
    return spamStatusHeader?.Value.toLowerCase().includes("yes") || false;
  }

  isNoReplySender(email: string): boolean {
    const localPart = email.split("@")[0]?.toLowerCase() || "";
    return this.noReplyLocalPartTokens.some((token) =>
      localPart.includes(token),
    );
  }

  hasAutoGeneratedHeader(body: IPostmarkInboundWebhook): boolean {
    const autoSubmittedHeader = body.Headers.find(
      (header) => header.Name.toLowerCase() === "auto-submitted",
    );
    if (
      autoSubmittedHeader &&
      autoSubmittedHeader.Value.toLowerCase() !== "no"
    ) {
      return true;
    }

    const precedenceHeader = body.Headers.find(
      (header) => header.Name.toLowerCase() === "precedence",
    );
    if (
      precedenceHeader &&
      this.autoGeneratedHeaderHints.some((hint) =>
        precedenceHeader.Value.toLowerCase().includes(hint),
      )
    ) {
      return true;
    }

    return body.Headers.some(
      (header) =>
        header.Name.toLowerCase() === "x-auto-response-suppress" ||
        header.Name.toLowerCase() === "list-unsubscribe",
    );
  }

  getHardSkipReason(body: IPostmarkInboundWebhook): string | null {
    if (this.isSpam(body)) {
      return "marked_as_spam";
    }
    if (this.isAutoReply(body)) {
      return "auto_reply";
    }
    if (this.isNoReplySender(body.FromFull.Email)) {
      return "no_reply_sender";
    }
    if (this.hasAutoGeneratedHeader(body)) {
      return "auto_generated_email";
    }
    return null;
  }
}

const postmarkParser = new PostmarkWebhookParser();
export default postmarkParser;
